# Generated by Django 5.1 on 2025-11-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="campaign name"),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="API key for marketplace integration (max 2048 chars)",
                        max_length=2048,
                        verbose_name="API key",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Error")],
                        default=2,
                        help_text="Campaign status: Active (1), Inactive (2), Error (3)",
                        verbose_name="status",
                    ),
                ),
                (
                    "marketplace",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Wildberries"), (2, "Ozon"), (3, "Yandex Market")],
                        help_text="Marketplace: Wildberries (1), Ozon (2), Yandex Market (3)",
                        null=True,
                        verbose_name="marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "campaigns",
                "ordering": ["-id"],
            },
        ),
    ]
