# Generated by Django 5.1 on 2025-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaign_created_at_campaign_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "Error"),
                    (4, "Paused"),
                    (5, "Stopped"),
                    (6, "Draft"),
                ],
                default=2,
                help_text="Campaign status: Active (1), Inactive (2), Error (3)",
                verbose_name="status",
            ),
        ),
    ]
