# Generated by Django 5.1 on 2025-11-23 01:13

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WildberriesAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Wildberries API key (encrypted)",
                        verbose_name="API key",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        help_text="Seller shop name on Wildberries",
                        max_length=255,
                        verbose_name="shop name",
                    ),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        help_text="Wildberries seller identifier",
                        max_length=100,
                        verbose_name="seller ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Account is active and can sync",
                        verbose_name="is active",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful synchronization timestamp",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "sync_frequency",
                    models.IntegerField(
                        default=60,
                        help_text="How often to sync data (minimum 15 minutes)",
                        validators=[django.core.validators.MinValueValidator(15)],
                        verbose_name="sync frequency (minutes)",
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically sync data at specified frequency",
                        verbose_name="auto sync enabled",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Wildberries Account",
                "verbose_name_plural": "Wildberries Accounts",
                "db_table": "wildberries_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WildberriesSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("campaigns", "Campaigns"),
                            ("statistics", "Statistics"),
                            ("products", "Products"),
                            ("full", "Full Sync"),
                        ],
                        max_length=20,
                        verbose_name="sync type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "campaigns_synced",
                    models.IntegerField(default=0, verbose_name="campaigns synced"),
                ),
                (
                    "statistics_synced",
                    models.IntegerField(
                        default=0, verbose_name="statistics records synced"
                    ),
                ),
                (
                    "products_synced",
                    models.IntegerField(default=0, verbose_name="products synced"),
                ),
                (
                    "errors_count",
                    models.IntegerField(default=0, verbose_name="errors count"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed error information",
                        verbose_name="error details",
                    ),
                ),
                (
                    "sync_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of synced data",
                        verbose_name="sync data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wildberries Sync Log",
                "verbose_name_plural": "Wildberries Sync Logs",
                "db_table": "wildberries_sync_logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
