# Generated by Django 5.1 on 2025-11-23 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wildberriesaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wildberries_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="wildberriessynclog",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="integrations.wildberriesaccount",
                verbose_name="account",
            ),
        ),
        migrations.AddIndex(
            model_name="wildberriesaccount",
            index=models.Index(
                fields=["user", "is_active"], name="wildberries_user_id_8aa9c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wildberriesaccount",
            index=models.Index(
                fields=["is_active", "auto_sync_enabled"],
                name="wildberries_is_acti_d8ccc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wildberriessynclog",
            index=models.Index(
                fields=["account", "status"], name="wildberries_account_822e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wildberriessynclog",
            index=models.Index(
                fields=["status", "started_at"], name="wildberries_status_f7866b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wildberriessynclog",
            index=models.Index(
                fields=["sync_type", "status"], name="wildberries_sync_ty_ec524e_idx"
            ),
        ),
    ]
