# Generated by Django 5.1 on 2025-11-23 01:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUserStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "total_impressions",
                    models.BigIntegerField(default=0, verbose_name="total impressions"),
                ),
                (
                    "total_clicks",
                    models.IntegerField(default=0, verbose_name="total clicks"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total spent",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "total_conversions",
                    models.IntegerField(default=0, verbose_name="total conversions"),
                ),
                (
                    "active_campaigns",
                    models.IntegerField(default=0, verbose_name="active campaigns"),
                ),
                (
                    "avg_ctr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="average CTR (%)",
                    ),
                ),
                (
                    "avg_roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="average ROI (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Daily User Statistic",
                "verbose_name_plural": "Daily User Statistics",
                "db_table": "daily_user_statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Marketplace product identifier",
                        max_length=100,
                        verbose_name="product ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="product name"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "views",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="views",
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="clicks",
                    ),
                ),
                (
                    "add_to_cart",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="add to cart",
                    ),
                ),
                (
                    "add_to_favorites",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="add to favorites",
                    ),
                ),
                (
                    "orders",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="orders",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="revenue",
                    ),
                ),
                (
                    "ad_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="ad spent",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="conversion rate (%)",
                    ),
                ),
                (
                    "acos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Advertising Cost of Sales",
                        max_digits=5,
                        verbose_name="ACoS (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Product Statistic",
                "verbose_name_plural": "Product Statistics",
                "db_table": "product_statistics",
                "ordering": ["-date", "-revenue"],
            },
        ),
        migrations.CreateModel(
            name="CampaignStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "impressions",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="impressions",
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="clicks",
                    ),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Click-through rate",
                        max_digits=5,
                        verbose_name="CTR (%)",
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="spent",
                    ),
                ),
                (
                    "cpc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per click",
                        max_digits=10,
                        verbose_name="CPC",
                    ),
                ),
                (
                    "conversions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="conversions",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="conversion rate (%)",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="revenue",
                    ),
                ),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Return on investment",
                        max_digits=10,
                        verbose_name="ROI (%)",
                    ),
                ),
                (
                    "add_to_cart",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="add to cart",
                    ),
                ),
                (
                    "cart_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="cart rate (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="campaigns.campaign",
                        verbose_name="campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Statistic",
                "verbose_name_plural": "Campaign Statistics",
                "db_table": "campaign_statistics",
                "ordering": ["-date"],
            },
        ),
    ]
