# Generated by Django 5.1 on 2025-11-23 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_initial"),
        ("statistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyuserstatistic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_statistics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="productstatistic",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_statistics",
                to="campaigns.campaign",
                verbose_name="campaign",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignstatistic",
            index=models.Index(
                fields=["campaign", "date"], name="campaign_st_campaig_205bd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignstatistic",
            index=models.Index(fields=["date"], name="campaign_st_date_ebb0c1_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignstatistic",
            index=models.Index(
                fields=["campaign", "-date"], name="campaign_st_campaig_12d596_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignstatistic",
            unique_together={("campaign", "date")},
        ),
        migrations.AddIndex(
            model_name="dailyuserstatistic",
            index=models.Index(
                fields=["user", "date"], name="daily_user__user_id_11cc16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyuserstatistic",
            index=models.Index(fields=["date"], name="daily_user__date_ffbcc1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyuserstatistic",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="productstatistic",
            index=models.Index(
                fields=["campaign", "date"], name="product_sta_campaig_e457ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstatistic",
            index=models.Index(
                fields=["product_id", "date"], name="product_sta_product_356006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstatistic",
            index=models.Index(
                fields=["campaign", "-revenue"], name="product_sta_campaig_64549b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstatistic",
            index=models.Index(fields=["date"], name="product_sta_date_4c9b1c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productstatistic",
            unique_together={("campaign", "product_id", "date")},
        ),
    ]
